# Generated by Django 3.2.7 on 2021-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_auto_20211213_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='user', to='hobbies.Hobby'),
        ),
    ]
